class ResString {
  var data ={
  'swipe' : 'Swipe and Select',
    'private' : 'Private',
    'public' : 'Public',
    'privateDescription': 'Non-Monetizable Visible to self and friends only',
    'publicDescription': 'Monetizable Visible to the entire network',
    'newPost': 'New Post',
    'travel': 'Travel',
    'food': 'Food',
    'both': 'Both',
    'experience': 'Your Experience',
    'searchtext': 'Search Location',
    'descriptionHintText': 'Description here....',
    'category': 'Category',
    'describe': 'Describe',
    'submitText': 'Submit',
    'appTitle': 'goDach',
    'connectingServer': 'Connection Server....',
    'suceessfulUpload': 'Successfully Upload',
    'successfulDescription': 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
    'done': 'Done',
    'descriptionRequired': 'Description Required',
    'placeNameRequired': 'Place Name Required',
    'importimage': 'Import Images/Video',
    'import': 'Import',
    'uploading': 'Uploading',
    'oneimagerequired': 'Atleast one image or video required',
    'appIntroHeadng1': 'Discover Experiences',
    'appIntroHeadng2': 'Trace your travels',
    'appIntroHeadng3': 'Share and Earn',
    'appIntroSubHeading1':
        'Swipe and Discover novel travel experiences through the eyes of your fellow wanderers.',
    'appIntroSubHeading2':
        'Store all your travel memories and never miss a chance to relive them.',
    'appIntroSubHeading3':
        'Share your travel stories and earn amazing rewards.',
    'privacy_policy': 'Privacy Policy',
    'term_of_uses': 'Term of use',
    'password': 'Password',
    'repeat_password': 'Repeat Password',
    'set_new_pass': 'Set New Password',
    'set_password': 'Set your 6-20 characters password',
    'enter_credential': 'Enter Credential',
    'confirm_that': ' and \nconfirm that you have read the ',
    'by_continue': 'By continuing, you agree to Payvor’s ',

    'password_not_match': 'Password and Confirm Password does not match',
    'confirm_password': 'Please enter confirm Password.',
    'pass_and_confirm_not_match': 'Password and Confirm Pssword does not match',
    'password_should_6_20_char': 'Password length should be 6-20 characters.',
    'forgot_password': 'Forgot Password',

    'full_name': 'Full Name',
    'reset_link': 'Send reset link',
    'login': 'Login',
    'sign_up': 'Sign up',
    'create_account': 'Create an Account',
    'enter_email': 'Please enter email address.',

    'enter_your_email': 'Enter your email and receive a link to reset your password',
    'join_the_community': 'Join the community here!',
    'enter_your_details': 'Enter your details to create an account',
    'sign_up_button': 'Sign Up',
    'login_button': 'LOGIN',
    'resend_code': 'RESEND CODE',
    'signup_cap_button': 'SIGN UP',
    'or_signup_with': 'or signup with',
    'enter_full_name': 'Please enter full name.',
    'already_have_Account': 'Already have an account? ',
    'welcome_back': 'Welcome back!',
    'remember_me': 'Remember me',
    'phone_number': 'Phone Number',
    'or_login_with': ' or login with',
    'dont_have_account': "Don't have an account? ",
    'forgot_pass': 'FORGOT PASSWORD?',
    'verify_number': 'Verify Phone Number',
    'enter_location': 'Please enter location.',
    'enter_phone_number': 'Please enter phone number.',
    'enter_ur_location': 'Enter your location and phone number',
    'verify_code': 'The verification code will expire in ',
    'enter_code_that': 'Please enter the code that is sent to your phone ',
    'to_continuew_plz': 'To continue, please verify your information',
    'new_password': 'New Password',
    'post_favor': 'Post Favor',
    'user_name': 'User Name',
    'enter_user_name': 'Please enter user name.',
    'enter_valid_user_name': 'Please enter a  user name between 3 to 10 characters.',
    'enter_password': 'Please enter password.',
    'enter_valid_password': 'Please enter a password  between 3 to 10 characters.',
  };
  String get(String key){
    return data[key];
  }
}

